/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AuthTokenTransformer from '#transformers/auth_token_transformer'

export namespace Data {
  export type AuthToken = InferData<AuthTokenTransformer>
  export namespace AuthToken {
    export type Variants = InferVariants<AuthTokenTransformer>
  }
}
